---
title: "5. Outcome Correlation Analysis and Heatmaps"
output: html_notebook
---

```{r}
## Modify outcomes table slightly ##

# Read the outcomes file
infection.outcomes = read.table('InputFiles/outcomes.txt', sep=',', header=T)

## Create data.frame which averages Isolate M values across all replicates found
# Create data.frame
MEs.noGrey.means = data.frame()

# Add means of M values taken from each respective replicate
MEs.noGrey.means=rbind(MEs.noGrey.means, colMeans(
  MEs.noGrey[,1:18][MEs.noGrey$Isolate == "Zt05",][MEs.noGrey$Stage == "A",], na.rm=TRUE))
MEs.noGrey.means=rbind(MEs.noGrey.means, colMeans(
  MEs.noGrey[,1:18][MEs.noGrey$Isolate == "Zt05",][MEs.noGrey$Stage == "B",], na.rm=TRUE))
MEs.noGrey.means=rbind(MEs.noGrey.means, colMeans(
  MEs.noGrey[,1:18][MEs.noGrey$Isolate == "Zt05",][MEs.noGrey$Stage == "C",], na.rm=TRUE))
MEs.noGrey.means=rbind(MEs.noGrey.means, colMeans(
  MEs.noGrey[,1:18][MEs.noGrey$Isolate == "Zt05",][MEs.noGrey$Stage == "D",], na.rm=TRUE))
MEs.noGrey.means=rbind(MEs.noGrey.means, colMeans(
  MEs.noGrey[,1:18][MEs.noGrey$Isolate == "Zt09",][MEs.noGrey$Stage == "A",], na.rm=TRUE))
MEs.noGrey.means=rbind(MEs.noGrey.means, colMeans(
  MEs.noGrey[,1:18][MEs.noGrey$Isolate == "Zt09",][MEs.noGrey$Stage == "B",], na.rm=TRUE))
MEs.noGrey.means=rbind(MEs.noGrey.means, colMeans(
  MEs.noGrey[,1:18][MEs.noGrey$Isolate == "Zt09",][MEs.noGrey$Stage == "C",], na.rm=TRUE))
MEs.noGrey.means=rbind(MEs.noGrey.means, colMeans(
  MEs.noGrey[,1:18][MEs.noGrey$Isolate == "Zt09",][MEs.noGrey$Stage == "D",], na.rm=TRUE))
MEs.noGrey.means=rbind(MEs.noGrey.means, colMeans(
  MEs.noGrey[,1:18][MEs.noGrey$Isolate == "Zt10",][MEs.noGrey$Stage == "A",], na.rm=TRUE))
MEs.noGrey.means=rbind(MEs.noGrey.means, colMeans(
  MEs.noGrey[,1:18][MEs.noGrey$Isolate == "Zt10",][MEs.noGrey$Stage == "B",], na.rm=TRUE))
MEs.noGrey.means=rbind(MEs.noGrey.means, colMeans(
  MEs.noGrey[,1:18][MEs.noGrey$Isolate == "Zt10",][MEs.noGrey$Stage == "C",], na.rm=TRUE))
MEs.noGrey.means=rbind(MEs.noGrey.means, colMeans(
  MEs.noGrey[,1:18][MEs.noGrey$Isolate == "Zt10",][MEs.noGrey$Stage == "D",], na.rm=TRUE))

MEs.noGrey.means=rbind(MEs.noGrey.means, colMeans(
  MEs.noGrey[,1:18][MEs.noGrey$Isolate == "X3D1" & MEs.noGrey$Stage == "A",], na.rm=TRUE))
MEs.noGrey.means=rbind(MEs.noGrey.means, colMeans(
  MEs.noGrey[,1:18][MEs.noGrey$Isolate == "X3D1" & MEs.noGrey$Stage == "B",], na.rm=TRUE))
MEs.noGrey.means=rbind(MEs.noGrey.means, colMeans(
  MEs.noGrey[,1:18][MEs.noGrey$Isolate == "X3D1" & MEs.noGrey$Stage == "C",], na.rm=TRUE))
MEs.noGrey.means=rbind(MEs.noGrey.means, colMeans(
  MEs.noGrey[,1:18][MEs.noGrey$Isolate == "X3D1" & MEs.noGrey$Stage == "D",], na.rm=TRUE))
MEs.noGrey.means=rbind(MEs.noGrey.means, colMeans(
  MEs.noGrey[,1:18][MEs.noGrey$Isolate == "X3D7" & MEs.noGrey$Stage == "A",], na.rm=TRUE))
MEs.noGrey.means=rbind(MEs.noGrey.means, colMeans(
  MEs.noGrey[,1:18][MEs.noGrey$Isolate == "X3D7" & MEs.noGrey$Stage == "B",], na.rm=TRUE))
MEs.noGrey.means=rbind(MEs.noGrey.means, colMeans(
  MEs.noGrey[,1:18][MEs.noGrey$Isolate == "X3D7" & MEs.noGrey$Stage == "C",], na.rm=TRUE))
MEs.noGrey.means=rbind(MEs.noGrey.means, colMeans(
  MEs.noGrey[,1:18][MEs.noGrey$Isolate == "X3D7" & MEs.noGrey$Stage == "D",], na.rm=TRUE))
MEs.noGrey.means=rbind(MEs.noGrey.means, colMeans(
  MEs.noGrey[,1:18][MEs.noGrey$Isolate == "X1A5" & MEs.noGrey$Stage == "A",], na.rm=TRUE))
MEs.noGrey.means=rbind(MEs.noGrey.means, colMeans(
  MEs.noGrey[,1:18][MEs.noGrey$Isolate == "X1A5" & MEs.noGrey$Stage == "B",], na.rm=TRUE))
MEs.noGrey.means=rbind(MEs.noGrey.means, colMeans(
  MEs.noGrey[,1:18][MEs.noGrey$Isolate == "X1A5" & MEs.noGrey$Stage == "C",], na.rm=TRUE))
MEs.noGrey.means=rbind(MEs.noGrey.means, colMeans(
  MEs.noGrey[,1:18][MEs.noGrey$Isolate == "X1A5" & MEs.noGrey$Stage == "D",], na.rm=TRUE))
MEs.noGrey.means=rbind(MEs.noGrey.means, colMeans(
  MEs.noGrey[,1:18][MEs.noGrey$Isolate == "X1E4" & MEs.noGrey$Stage == "A",], na.rm=TRUE))
MEs.noGrey.means=rbind(MEs.noGrey.means, colMeans(
  MEs.noGrey[,1:18][MEs.noGrey$Isolate == "X1E4" & MEs.noGrey$Stage == "B",], na.rm=TRUE))
MEs.noGrey.means=rbind(MEs.noGrey.means, colMeans(
  MEs.noGrey[,1:18][MEs.noGrey$Isolate == "X1E4" & MEs.noGrey$Stage == "C",], na.rm=TRUE))
MEs.noGrey.means=rbind(MEs.noGrey.means, colMeans(
  MEs.noGrey[,1:18][MEs.noGrey$Isolate == "X1E4" & MEs.noGrey$Stage == "D",], na.rm=TRUE))

# Add col & rownames
colnames(MEs.noGrey.means) = colnames(MEs.noGrey[,1:18])
rownames(MEs.noGrey.means) = unique(paste(MEs.noGrey$Isolate, MEs.noGrey$Stage, sep = "_"))
# Reorder columns M1 -> M26
MEs.noGrey.means = MEs.noGrey.means[,stri_sort(colnames(MEs.noGrey.means), numeric = T)]

write.table(MEs.noGrey, file = "Tables/Ms.noGrey.txt", sep = "\t")

```


```{r}
# Create an eignegene data frame for each stage of the infection process
eig.A = data.frame(MEs.noGrey.means[stri_detect(rownames(MEs.noGrey.means), regex = "_A"),])
eig.B = data.frame(MEs.noGrey.means[stri_detect(rownames(MEs.noGrey.means), regex = "_B"),])
eig.C = data.frame(MEs.noGrey.means[stri_detect(rownames(MEs.noGrey.means), regex = "_C"),])
eig.D = data.frame(MEs.noGrey.means[stri_detect(rownames(MEs.noGrey.means), regex = "_D"),])

# Calculate correlations between eigengenes and infection outcomes
eig.A.corAndP = corAndPvalue(eig.A, infection.outcomes[,2:5], use = "pairwise.complete.obs", alternative = c("two.sided"))
eig.B.corAndP = corAndPvalue(eig.B, infection.outcomes[,2:5], use = "pairwise.complete.obs", alternative = c("two.sided"))
eig.C.corAndP = corAndPvalue(eig.C, infection.outcomes[,2:5], use = "pairwise.complete.obs", alternative = c("two.sided"))
eig.D.corAndP = corAndPvalue(eig.D, infection.outcomes[,2:5], use = "pairwise.complete.obs", alternative = c("two.sided"))

```

```{r}
# eig.A Heatmap
textMatrix = paste(signif(eig.A.corAndP$p, 2), "\n(", signif(eig.A.corAndP$cor, 2), ")", sep = "")
dim(textMatrix) = dim(eig.A.corAndP$cor)
jpeg(file = "Plots/Heatmaps/eig.A.jpeg", width = 400, height = 800)
par(mar = c(5, 3, 3, 2))
labeledHeatmap(Matrix = eig.A.corAndP$cor,
xLabels = c("Necrosis\ndevelopment", "Pycnidia\ndevelopment", "Necrosis\nlevel", "Early\nonset"),
yLabels = names(MEs.noGrey.means),
xLabelsAngle = 90,
textAdj = c(0.5,0.5),
colorLabels = FALSE,
colors = blueWhiteRed(50),
textMatrix = textMatrix,
setStdMargins = FALSE,
plotLegend = FALSE,
keepLegendSpace = TRUE,
cex.text = 1,
zlim = c(-1,1),
main = "(a)", 
adj = 0,
cex.main = 2)
dev.off()

# eig.B Heatmap
textMatrix = paste(signif(eig.B.corAndP$p, 2), "\n(", signif(eig.B.corAndP$cor, 2), ")", sep = "")
dim(textMatrix) = dim(eig.B.corAndP$cor)
jpeg(file = "Plots/Heatmaps/eig.B.jpeg", width = 400, height = 800)
par(mar = c(5, 3, 3, 2))
labeledHeatmap(Matrix = eig.B.corAndP$cor,
xLabels = c("Necrosis\ndevelopment", "Pycnidia\ndevelopment", "Necrosis\nlevel", "Early\nonset"),
yLabels = names(MEs.noGrey.means),
xLabelsAngle = 90,
textAdj = c(0.5,0.5),
colorLabels = FALSE,
colors = blueWhiteRed(50),
textMatrix = textMatrix,
setStdMargins = FALSE,
plotLegend = FALSE,
keepLegendSpace = TRUE,
cex.text = 1,
zlim = c(-1,1),
main = "(b)", 
adj = 0,
cex.main = 2)
dev.off()

# eig.C Heatmap
textMatrix = paste(signif(eig.C.corAndP$p, 2), "\n(", signif(eig.C.corAndP$cor, 2), ")", sep = "")
dim(textMatrix) = dim(eig.C.corAndP$cor)
jpeg(file = "Plots/Heatmaps/eig.C.jpeg", width = 400, height = 800)
par(mar = c(5, 3, 3, 2)) 
labeledHeatmap(Matrix = eig.C.corAndP$cor,
xLabels = c("Necrosis\ndevelopment", "Pycnidia\ndevelopment", "Necrosis\nlevel", "Early\nonset"),
yLabels = names(MEs.noGrey.means),
xLabelsAngle = 90,
textAdj = c(0.5,0.5),
colorLabels = FALSE,
colors = blueWhiteRed(50),
textMatrix = textMatrix,
setStdMargins = FALSE,
plotLegend = FALSE,
keepLegendSpace = TRUE,
cex.text = 1,
zlim = c(-1,1),
main = "(c)", 
adj = 0,
cex.main = 2)
dev.off()

# eig.D Heatmap
textMatrix = paste(signif(eig.D.corAndP$p, 2), "\n(", signif(eig.D.corAndP$cor, 2), ")", sep = "")
dim(textMatrix) = dim(eig.D.corAndP$cor)
jpeg(file = "Plots/Heatmaps/eig.D.jpeg", width = 400, height = 800)
par(mar = c(5, 3, 3, 2))
labeledHeatmap(Matrix = eig.D.corAndP$cor,
xLabels = c("Necrosis\ndevelopment", "Pycnidia\ndevelopment", "Necrosis\nlevel", "Early\nonset"),
yLabels = names(MEs.noGrey.means),
xLabelsAngle = 90,
textAdj = c(0.5,0.5),
colorLabels = FALSE,
colors = blueWhiteRed(50),
textMatrix = textMatrix,
setStdMargins = FALSE,
cex.text = 1,
zlim = c(-1,1),
main = "(d)", 
adj = 0,
cex.main = 2)
dev.off()

```

```{r}
## Module Pairwise Co-Expression Heatmaps ##

# Reorder rows M1 -> M26
B.vs.A$MEs = gsub("M", "", B.vs.A$MEs)
B.vs.A$MEs = as.numeric(B.vs.A$MEs)
B.vs.A = B.vs.A[order(B.vs.A$MEs),]

C.vs.B$MEs = gsub("M", "", C.vs.B$MEs)
C.vs.B$MEs = as.numeric(C.vs.B$MEs)
C.vs.B = C.vs.B[order(C.vs.B$MEs),]

D.vs.C$MEs = gsub("M", "", D.vs.C$MEs)
D.vs.C$MEs = as.numeric(D.vs.C$MEs)
D.vs.C = D.vs.C[order(D.vs.C$MEs),]

# B.vs.A Heatmap
textMatrix = paste(signif(B.vs.A$logFC, 2), "\n(", signif(B.vs.A$adj.P.Val, 2), ")", sep = "")
dim(textMatrix) = c(18, 1)
jpeg(file = "Plots/Heatmaps/B.vs.A.jpeg", width = 200, height = 800)
par(mar = c(5, 3, 3, 2))
labeledHeatmap(Matrix = B.vs.A[,2],
xLabels = NA,
yLabels = names(MEs.noGrey.means),
xLabelsAngle = 90,
textAdj = c(0.5,0.5),
colorLabels = FALSE,
colors = blueWhiteRed(50),
textMatrix = textMatrix,
setStdMargins = FALSE,
plotLegend = FALSE,
keepLegendSpace = TRUE,
cex.text = 1,
zlim = c(-1,1),
main = "B.vs.A",
adj = 0,
cex.main = 1.5)
dev.off()

# C.vs.B Heatmap
textMatrix = paste(signif(C.vs.B$logFC, 2), "\n(", signif(C.vs.B$adj.P.Val, 2), ")", sep = "")
dim(textMatrix) = c(18, 1)
jpeg(file = "Plots/Heatmaps/C.vs.B.jpeg", width = 200, height = 800)
par(mar = c(5, 3, 3, 2))
labeledHeatmap(Matrix = C.vs.B[,2],
xLabels = NA,
yLabels = names(MEs.noGrey.means),
xLabelsAngle = 90,
textAdj = c(0.5,0.5),
colorLabels = FALSE,
colors = blueWhiteRed(50),
textMatrix = textMatrix,
setStdMargins = FALSE,
plotLegend = FALSE,
keepLegendSpace = TRUE,
cex.text = 1,
zlim = c(-1,1),
main = "C.vs.B",
adj = 0,
cex.main = 1.5)
dev.off()

# D.vs.C Heatmap
textMatrix = paste(signif(D.vs.C$logFC, 2), "\n(", signif(D.vs.C$adj.P.Val, 2), ")", sep = "")
dim(textMatrix) = c(18, 1)
jpeg(file = "Plots/Heatmaps/D.vs.C.jpeg", width = 200, height = 800)
par(mar = c(5, 3, 3, 2))
labeledHeatmap(Matrix = D.vs.C[,2],
xLabels = NA,
yLabels = names(MEs.noGrey.means),
xLabelsAngle = 90,
textAdj = c(0.5,0.5),
colorLabels = FALSE,
colors = blueWhiteRed(50),
textMatrix = textMatrix,
setStdMargins = FALSE,
keepLegendSpace = TRUE,
cex.text = 1,
zlim = c(-1,1),
main = "D.vs.C",
adj = 0,
cex.main = 1.5)
dev.off()

```

```{r}
#### DRAW SCATTERPLOTS OF SIGNIFICANT ME OUTCOMES ####

## Signif list of modules and fields affected ##
# A.ME24.Pycnidia
# B.ME13.Necrosis.lvl/Early.onset
# B.ME24.Pycnidia
# C.ME6.Necrosis.lvl/Early.onset
# C.ME13.Necrosis.lvl/Early.onset
# C.ME24.Pycnidia
# D.ME24.Pycnidia


# A.ME24.Pycnidia
eig.A.ME24 = eig.A[colnames(eig.A)==c("M24")]
eig.A.ME24$Pycnidia.dpi = NA
eig.A.ME24$Group = NA
for (x in 1:length(eig.A.ME24$Pycnidia.dpi)){
  if(stri_detect(rownames(eig.A.ME24)[x], regex = "3D1")) {
    eig.A.ME24$Pycnidia.dpi[x] =  infection.outcomes$Pycnidia..dpi.[infection.outcomes$Isolate == "3D1"]
    eig.A.ME24$Group[x] = "PG"
  } 
  if(stri_detect(rownames(eig.A.ME24)[x], regex = "3D7")) {
    eig.A.ME24$Pycnidia.dpi[x] =  infection.outcomes$Pycnidia..dpi.[infection.outcomes$Isolate == "3D7"]
    eig.A.ME24$Group[x] = "PG"
  } 
  if(stri_detect(rownames(eig.A.ME24)[x], regex = "1A5")) {
    eig.A.ME24$Pycnidia.dpi[x] =  infection.outcomes$Pycnidia..dpi.[infection.outcomes$Isolate == "1A5"]
    eig.A.ME24$Group[x] = "PG"
  } 
  if(stri_detect(rownames(eig.A.ME24)[x], regex = "1E4")) {
    eig.A.ME24$Pycnidia.dpi[x] =  infection.outcomes$Pycnidia..dpi.[infection.outcomes$Isolate == "1E4"]
    eig.A.ME24$Group[x] = "PG"
  } 
  if(stri_detect(rownames(eig.A.ME24)[x], regex = "Zt05")) {
    eig.A.ME24$Pycnidia.dpi[x] =  infection.outcomes$Pycnidia..dpi.[infection.outcomes$Isolate == "Zt05"]
    eig.A.ME24$Group[x] = "H"
  } 
  if(stri_detect(rownames(eig.A.ME24)[x], regex = "Zt09")) {
    eig.A.ME24$Pycnidia.dpi[x] =  infection.outcomes$Pycnidia..dpi.[infection.outcomes$Isolate == "Zt09"]
    eig.A.ME24$Group[x] = "H"
  } 
  if(stri_detect(rownames(eig.A.ME24)[x], regex = "Zt10")) {
    eig.A.ME24$Pycnidia.dpi[x] =  infection.outcomes$Pycnidia..dpi.[infection.outcomes$Isolate == "Zt10"]
    eig.A.ME24$Group[x] = "H"
  }
}

jpeg(filename = "Plots/eigscatterplots/A.Pycnidia.M24.jpeg")
ggplot(eig.A.ME24, aes(y=Pycnidia.dpi, x=M24)) +
  geom_smooth(method=lm , color="grey", fill='lightgrey', se=TRUE) +
  geom_point(aes(color = Group, shape = rownames(eig.A.ME24)), size = 3) +
  scale_shape_manual(values = c(15,6,19,5,17,9,18), name = "Isolates", labels = c("1A5", "1E4", "3D1", "3D7", "Zt05", "Zt09", "Zt10")) +
  ggtitle("M24.A: Pycnidia development") +
  xlab("Eigengene expression")
dev.off()

# B.ME13.Necrosis.lvl/Early.onset
eig.B.ME13 = eig.B[colnames(eig.B)==c("M13")]
eig.B.ME13$Necrosis.level = NA
eig.B.ME13$Early.onset = NA
eig.B.ME13$Group = NA
for (x in 1:length(eig.B.ME13$Necrosis.level)){
  if(stri_detect(rownames(eig.B.ME13)[x], regex = "3D1")) {
    eig.B.ME13$Necrosis.level[x] =  infection.outcomes$Necrosis.level[infection.outcomes$Isolate == "3D1"]
    eig.B.ME13$Early.onset[x] =  infection.outcomes$Early.onset[infection.outcomes$Isolate == "3D1"]
    eig.B.ME13$Group[x] = "PG"
  } 
  if(stri_detect(rownames(eig.B.ME13)[x], regex = "3D7")) {
    eig.B.ME13$Necrosis.level[x] =  infection.outcomes$Necrosis.level[infection.outcomes$Isolate == "3D7"]
    eig.B.ME13$Early.onset[x] =  infection.outcomes$Early.onset[infection.outcomes$Isolate == "3D7"]
    eig.B.ME13$Group[x] = "PG"
  } 
  if(stri_detect(rownames(eig.B.ME13)[x], regex = "1A5")) {
    eig.B.ME13$Necrosis.level[x] =  infection.outcomes$Necrosis.level[infection.outcomes$Isolate == "1A5"]
    eig.B.ME13$Early.onset[x] =  infection.outcomes$Early.onset[infection.outcomes$Isolate == "1A5"]
    eig.B.ME13$Group[x] = "PG"
  } 
  if(stri_detect(rownames(eig.B.ME13)[x], regex = "1E4")) {
    eig.B.ME13$Necrosis.level[x] =  infection.outcomes$Necrosis.level[infection.outcomes$Isolate == "1E4"]
    eig.B.ME13$Early.onset[x] =  infection.outcomes$Early.onset[infection.outcomes$Isolate == "1E4"]
    eig.B.ME13$Group[x] = "PG"
  } 
  if(stri_detect(rownames(eig.B.ME13)[x], regex = "Zt05")) {
    eig.B.ME13$Necrosis.level[x] =  infection.outcomes$Necrosis.level[infection.outcomes$Isolate == "Zt05"]
    eig.B.ME13$Early.onset[x] =  infection.outcomes$Early.onset[infection.outcomes$Isolate == "Zt05"]
    eig.B.ME13$Group[x] = "H"
  } 
  if(stri_detect(rownames(eig.B.ME13)[x], regex = "Zt09")) {
    eig.B.ME13$Necrosis.level[x] =  infection.outcomes$Necrosis.level[infection.outcomes$Isolate == "Zt09"]
    eig.B.ME13$Early.onset[x] =  infection.outcomes$Early.onset[infection.outcomes$Isolate == "Zt09"]
    eig.B.ME13$Group[x] = "H"
  } 
  if(stri_detect(rownames(eig.B.ME13)[x], regex = "Zt10")) {
    eig.B.ME13$Necrosis.level[x] =  infection.outcomes$Necrosis.level[infection.outcomes$Isolate == "Zt10"]
    eig.B.ME13$Early.onset[x] =  infection.outcomes$Early.onset[infection.outcomes$Isolate == "Zt10"]
    eig.B.ME13$Group[x] = "H"
  }
}

jpeg(filename = "Plots/eigscatterplots/B.NecrosisLvl.M13.jpeg")
ggplot(eig.B.ME13, aes(y=Necrosis.level, x=M13)) +
  geom_smooth(method=lm , color="grey", fill='lightgrey', se=TRUE) +
  geom_point(aes(color = Group, shape = rownames(eig.B.ME13)), size = 3) +
  scale_shape_manual(values = c(15,6,19,5,17,9,18), name = "Isolates", labels = c("1A5", "1E4", "3D1", "3D7", "Zt05", "Zt09", "Zt10")) +
  ggtitle("ME13.B: Final Necrosis Level") +
  xlab("Eigengene expression")
dev.off()

jpeg(filename = "Plots/eigscatterplots/B.EarlyOnset.M13.jpeg")
ggplot(eig.B.ME13, aes(y=Early.onset, x=M13)) +
  geom_smooth(method=lm , color="grey", fill='lightgrey', se=TRUE) +
  geom_point(aes(color = Group, shape = rownames(eig.B.ME13)), size = 3) +
  scale_shape_manual(values = c(15,6,19,5,17,9,18), name = "Isolates", labels = c("1A5", "1E4", "3D1", "3D7", "Zt05", "Zt09", "Zt10")) +
  ggtitle("M13.B: Early Onset") +
  xlab("Eigengene expression")
dev.off()

# B.ME24.Pycnidia
eig.B.ME24 = eig.B[colnames(eig.B)==c("M24")]
eig.B.ME24$Pycnidia.dpi = NA
eig.B.ME24$Group = NA
for (x in 1:length(eig.B.ME24$Pycnidia.dpi)){
  if(stri_detect(rownames(eig.B.ME24)[x], regex = "3D1")) {
    eig.B.ME24$Pycnidia.dpi[x] =  infection.outcomes$Pycnidia..dpi.[infection.outcomes$Isolate == "3D1"]
    eig.B.ME24$Group[x] = "PG"
  } 
  if(stri_detect(rownames(eig.B.ME24)[x], regex = "3D7")) {
    eig.B.ME24$Pycnidia.dpi[x] =  infection.outcomes$Pycnidia..dpi.[infection.outcomes$Isolate == "3D7"]
    eig.B.ME24$Group[x] = "PG"
  } 
  if(stri_detect(rownames(eig.B.ME24)[x], regex = "1A5")) {
    eig.B.ME24$Pycnidia.dpi[x] =  infection.outcomes$Pycnidia..dpi.[infection.outcomes$Isolate == "1A5"]
    eig.B.ME24$Group[x] = "PG"
  } 
  if(stri_detect(rownames(eig.B.ME24)[x], regex = "1E4")) {
    eig.B.ME24$Pycnidia.dpi[x] =  infection.outcomes$Pycnidia..dpi.[infection.outcomes$Isolate == "1E4"]
    eig.B.ME24$Group[x] = "PG"
  } 
  if(stri_detect(rownames(eig.B.ME24)[x], regex = "Zt05")) {
    eig.B.ME24$Pycnidia.dpi[x] =  infection.outcomes$Pycnidia..dpi.[infection.outcomes$Isolate == "Zt05"]
    eig.B.ME24$Group[x] = "H"
  } 
  if(stri_detect(rownames(eig.B.ME24)[x], regex = "Zt09")) {
    eig.B.ME24$Pycnidia.dpi[x] =  infection.outcomes$Pycnidia..dpi.[infection.outcomes$Isolate == "Zt09"]
    eig.B.ME24$Group[x] = "H"
  } 
  if(stri_detect(rownames(eig.B.ME24)[x], regex = "Zt10")) {
    eig.B.ME24$Pycnidia.dpi[x] =  infection.outcomes$Pycnidia..dpi.[infection.outcomes$Isolate == "Zt10"]
    eig.B.ME24$Group[x] = "H"
  }
}

jpeg(filename = "Plots/eigscatterplots/B.Pycnidia.M24.jpeg")
ggplot(eig.B.ME24, aes(y=Pycnidia.dpi, x=M24)) +
  geom_smooth(method=lm , color="grey", fill='lightgrey', se=TRUE) +
  geom_point(aes(color = Group, shape = rownames(eig.B.ME24)), size = 3) +
  scale_shape_manual(values = c(15,6,19,5,17,9,18), name = "Isolates", labels = c("1A5", "1E4", "3D1", "3D7", "Zt05", "Zt09", "Zt10")) +
  ggtitle("M24.B: Pycnidia development") +
  xlab("Eigengene expression")
dev.off()

# C.ME6.Necrosis.lvl/Early.onset
eig.C.ME6 = eig.C[colnames(eig.C)==c("M6")]
eig.C.ME6$Necrosis.level = NA
eig.C.ME6$Early.onset = NA
eig.C.ME6$Group = NA
for (x in 1:length(eig.C.ME6$Necrosis.level)){
  if(stri_detect(rownames(eig.C.ME6)[x], regex = "3D1")) {
    eig.C.ME6$Necrosis.level[x] =  infection.outcomes$Necrosis.level[infection.outcomes$Isolate == "3D1"]
    eig.C.ME6$Early.onset[x] =  infection.outcomes$Early.onset[infection.outcomes$Isolate == "3D1"]
    eig.C.ME6$Group[x] = "PG"
  } 
  if(stri_detect(rownames(eig.C.ME6)[x], regex = "3D7")) {
    eig.C.ME6$Necrosis.level[x] =  infection.outcomes$Necrosis.level[infection.outcomes$Isolate == "3D7"]
    eig.C.ME6$Early.onset[x] =  infection.outcomes$Early.onset[infection.outcomes$Isolate == "3D7"]
    eig.C.ME6$Group[x] = "PG"
  } 
  if(stri_detect(rownames(eig.C.ME6)[x], regex = "1A5")) {
    eig.C.ME6$Necrosis.level[x] =  infection.outcomes$Necrosis.level[infection.outcomes$Isolate == "1A5"]
    eig.C.ME6$Early.onset[x] =  infection.outcomes$Early.onset[infection.outcomes$Isolate == "1A5"]
    eig.C.ME6$Group[x] = "PG"
  } 
  if(stri_detect(rownames(eig.C.ME6)[x], regex = "1E4")) {
    eig.C.ME6$Necrosis.level[x] =  infection.outcomes$Necrosis.level[infection.outcomes$Isolate == "1E4"]
    eig.C.ME6$Early.onset[x] =  infection.outcomes$Early.onset[infection.outcomes$Isolate == "1E4"]
    eig.C.ME6$Group[x] = "PG"
  } 
  if(stri_detect(rownames(eig.C.ME6)[x], regex = "Zt05")) {
    eig.C.ME6$Necrosis.level[x] =  infection.outcomes$Necrosis.level[infection.outcomes$Isolate == "Zt05"]
    eig.C.ME6$Early.onset[x] =  infection.outcomes$Early.onset[infection.outcomes$Isolate == "Zt05"]
    eig.C.ME6$Group[x] = "H"
  } 
  if(stri_detect(rownames(eig.C.ME6)[x], regex = "Zt09")) {
    eig.C.ME6$Necrosis.level[x] =  infection.outcomes$Necrosis.level[infection.outcomes$Isolate == "Zt09"]
    eig.C.ME6$Early.onset[x] =  infection.outcomes$Early.onset[infection.outcomes$Isolate == "Zt09"]
    eig.C.ME6$Group[x] = "H"
  } 
  if(stri_detect(rownames(eig.C.ME6)[x], regex = "Zt10")) {
    eig.C.ME6$Necrosis.level[x] =  infection.outcomes$Necrosis.level[infection.outcomes$Isolate == "Zt10"]
    eig.C.ME6$Early.onset[x] =  infection.outcomes$Early.onset[infection.outcomes$Isolate == "Zt10"]
    eig.C.ME6$Group[x] = "H"
  }
}

jpeg(filename = "Plots/eigscatterplots/C.NecrosisLvl.M6.jpeg")
ggplot(eig.C.ME6, aes(y=Necrosis.level, x=M6)) +
  geom_smooth(method=lm , color="grey", fill='lightgrey', se=TRUE) +
  geom_point(aes(color = Group, shape = rownames(eig.C.ME6)), size = 3) +
  scale_shape_manual(values = c(15,6,19,5,17,9,18), name = "Isolates", labels = c("1A5", "1E4", "3D1", "3D7", "Zt05", "Zt09", "Zt10")) +
  ggtitle("M6.C: Final Necrosis Level") +
  xlab("Eigengene expression")
dev.off()

jpeg(filename = "Plots/eigscatterplots/C.EarlyOnset.M6.jpeg")
ggplot(eig.C.ME6, aes(y=Early.onset, x=M6)) +
  geom_smooth(method=lm , color="grey", fill='lightgrey', se=TRUE) +
  geom_point(aes(color = Group, shape = rownames(eig.C.ME6)), size = 3) +
  scale_shape_manual(values = c(15,6,19,5,17,9,18), name = "Isolates", labels = c("1A5", "1E4", "3D1", "3D7", "Zt05", "Zt09", "Zt10")) +
  ggtitle("M6.C: Early Onset") +
  xlab("Eigengene expression")
dev.off()

# C.ME13.Necrosis/Necrosis.lvl/Early.onset -> cowplot these
eig.C.ME13 = eig.C[colnames(eig.C)==c("M13")]
eig.C.ME13$Necrosis.dpi = NA
eig.C.ME13$Necrosis.level = NA
eig.C.ME13$Early.onset = NA
eig.C.ME13$Group = NA
for (x in 1:length(eig.C.ME13$Necrosis.level)){
  if(stri_detect(rownames(eig.C.ME13)[x], regex = "3D1")) {
    eig.C.ME13$Necrosis.dpi[x] =  infection.outcomes$Necrosis..dpi.[infection.outcomes$Isolate == "3D1"]
    eig.C.ME13$Necrosis.level[x] =  infection.outcomes$Necrosis.level[infection.outcomes$Isolate == "3D1"]
    eig.C.ME13$Early.onset[x] =  infection.outcomes$Early.onset[infection.outcomes$Isolate == "3D1"]
    eig.C.ME13$Group[x] = "PG"
  } 
  if(stri_detect(rownames(eig.C.ME13)[x], regex = "3D7")) {
    eig.C.ME13$Necrosis.dpi[x] =  infection.outcomes$Necrosis..dpi.[infection.outcomes$Isolate == "3D7"]
    eig.C.ME13$Necrosis.level[x] =  infection.outcomes$Necrosis.level[infection.outcomes$Isolate == "3D7"]
    eig.C.ME13$Early.onset[x] =  infection.outcomes$Early.onset[infection.outcomes$Isolate == "3D7"]
    eig.C.ME13$Group[x] = "PG"
  } 
  if(stri_detect(rownames(eig.C.ME13)[x], regex = "1A5")) {
    eig.C.ME13$Necrosis.dpi[x] =  infection.outcomes$Necrosis..dpi.[infection.outcomes$Isolate == "1A5"]
    eig.C.ME13$Necrosis.level[x] =  infection.outcomes$Necrosis.level[infection.outcomes$Isolate == "1A5"]
    eig.C.ME13$Early.onset[x] =  infection.outcomes$Early.onset[infection.outcomes$Isolate == "1A5"]
    eig.C.ME13$Group[x] = "PG"
  } 
  if(stri_detect(rownames(eig.C.ME13)[x], regex = "1E4")) {
    eig.C.ME13$Necrosis.dpi[x] =  infection.outcomes$Necrosis..dpi.[infection.outcomes$Isolate == "1E4"]
    eig.C.ME13$Necrosis.level[x] =  infection.outcomes$Necrosis.level[infection.outcomes$Isolate == "1E4"]
    eig.C.ME13$Early.onset[x] =  infection.outcomes$Early.onset[infection.outcomes$Isolate == "1E4"]
    eig.C.ME13$Group[x] = "PG"
  } 
  if(stri_detect(rownames(eig.C.ME13)[x], regex = "Zt05")) {
    eig.C.ME13$Necrosis.dpi[x] =  infection.outcomes$Necrosis..dpi.[infection.outcomes$Isolate == "Zt05"]
    eig.C.ME13$Necrosis.level[x] =  infection.outcomes$Necrosis.level[infection.outcomes$Isolate == "Zt05"]
    eig.C.ME13$Early.onset[x] =  infection.outcomes$Early.onset[infection.outcomes$Isolate == "Zt05"]
    eig.C.ME13$Group[x] = "H"
  } 
  if(stri_detect(rownames(eig.C.ME13)[x], regex = "Zt09")) {
    eig.C.ME13$Necrosis.dpi[x] =  infection.outcomes$Necrosis..dpi.[infection.outcomes$Isolate == "Zt09"]
    eig.C.ME13$Necrosis.level[x] =  infection.outcomes$Necrosis.level[infection.outcomes$Isolate == "Zt09"]
    eig.C.ME13$Early.onset[x] =  infection.outcomes$Early.onset[infection.outcomes$Isolate == "Zt09"]
    eig.C.ME13$Group[x] = "H"
  } 
  if(stri_detect(rownames(eig.C.ME13)[x], regex = "Zt10")) {
    eig.C.ME13$Necrosis.dpi[x] =  infection.outcomes$Necrosis..dpi.[infection.outcomes$Isolate == "Zt10"]
    eig.C.ME13$Necrosis.level[x] =  infection.outcomes$Necrosis.level[infection.outcomes$Isolate == "Zt10"]
    eig.C.ME13$Early.onset[x] =  infection.outcomes$Early.onset[infection.outcomes$Isolate == "Zt10"]
    eig.C.ME13$Group[x] = "H"
  }
}

M13.C.list = list()
jpeg(filename = "Plots/eigscatterplots/C.Necrosis.M13.jpeg")
M13.C.list[[1]] = ggplot(eig.C.ME13, aes(y=Necrosis.dpi, x=M13)) +
  geom_smooth(method=lm , color="grey", fill='lightgrey', se=TRUE) +
  geom_point(aes(color = Group, shape = rownames(eig.C.ME13)), size = 2, show.legend = F) +
  scale_shape_manual(values = c(15,6,19,5,17,9,18), name = "Isolates", labels = c("1A5", "1E4", "3D1", "3D7", "Zt05", "Zt09", "Zt10")) +
  ggtitle("Necrosis development", subtitle = bquote("R"^2~ "="~ -0.69)) +
  theme(plot.title = element_text(size = 12)) +
  xlab("Eigengene expression")
dev.off()

jpeg(filename = "Plots/eigscatterplots/C.NecrosisLvl.M13.jpeg")
M13.C.list[[2]] = ggplot(eig.C.ME13, aes(y=Necrosis.level, x=M13)) +
  geom_smooth(method=lm , color="grey", fill='lightgrey', se=TRUE) +
  geom_point(aes(color = Group, shape = rownames(eig.C.ME13)), size = 2, show.legend = F) +
  scale_shape_manual(values = c(15,6,19,5,17,9,18), name = "Isolates", labels = c("1A5", "1E4", "3D1", "3D7", "Zt05", "Zt09", "Zt10")) +
  ggtitle("Final Necrosis Level", subtitle = bquote("R"^2~ "="~ 0.83)) +
  theme(plot.title = element_text(size = 12)) +
  xlab("Eigengene expression")
dev.off()


jpeg(filename = "Plots/eigscatterplots/C.EarlyOnset.M13.jpeg")
M13.C.list[[3]] = ggplot(eig.C.ME13, aes(y=Early.onset, x=M13)) +
  geom_smooth(method=lm , color="grey", fill='lightgrey', se=TRUE) +
  geom_point(aes(color = Group, shape = rownames(eig.C.ME13)), size = 2) +
  scale_shape_manual(values = c(15,6,19,5,17,9,18), name = "Isolates", labels = c("1A5", "1E4", "3D1", "3D7", "Zt05", "Zt09", "Zt10")) +
  ggtitle("Early Onset", subtitle = bquote("R"^2~ "="~ 0.83)) +
  theme(plot.title = element_text(size = 12)) +
  xlab("Eigengene expression") +
  theme(legend.key.size = unit(0.5, 'cm'), legend.text = element_text(size=8), legend.title = element_text(size=10))
dev.off()


## cowplot of M13.C infection outcome graphs
jpeg(file = "Plots/eigscatterplots/M13.C.Figure.jpeg", width = 650, height = 325, res = 95)
plot = plot_grid(plotlist = M13.C.list, nrow = 1, labels = c('(a)', '(b)', '(c)'), label_size = 14, scale = 0.98)
ggdraw(plot)
dev.off()

# C.ME24.Pycnidia
eig.C.ME24 = eig.C[colnames(eig.C)==c("M24")]
eig.C.ME24$Pycnidia.dpi = NA
eig.C.ME24$Group = NA
for (x in 1:length(eig.C.ME24$Pycnidia.dpi)){
  if(stri_detect(rownames(eig.C.ME24)[x], regex = "3D1")) {
    eig.C.ME24$Pycnidia.dpi[x] =  infection.outcomes$Pycnidia..dpi.[infection.outcomes$Isolate == "3D1"]
    eig.C.ME24$Group[x] = "PG"
  } 
  if(stri_detect(rownames(eig.C.ME24)[x], regex = "3D7")) {
    eig.C.ME24$Pycnidia.dpi[x] =  infection.outcomes$Pycnidia..dpi.[infection.outcomes$Isolate == "3D7"]
    eig.C.ME24$Group[x] = "PG"
  } 
  if(stri_detect(rownames(eig.C.ME24)[x], regex = "1A5")) {
    eig.C.ME24$Pycnidia.dpi[x] =  infection.outcomes$Pycnidia..dpi.[infection.outcomes$Isolate == "1A5"]
    eig.C.ME24$Group[x] = "PG"
  } 
  if(stri_detect(rownames(eig.C.ME24)[x], regex = "1E4")) {
    eig.C.ME24$Pycnidia.dpi[x] =  infection.outcomes$Pycnidia..dpi.[infection.outcomes$Isolate == "1E4"]
    eig.C.ME24$Group[x] = "PG"
  } 
  if(stri_detect(rownames(eig.C.ME24)[x], regex = "Zt05")) {
    eig.C.ME24$Pycnidia.dpi[x] =  infection.outcomes$Pycnidia..dpi.[infection.outcomes$Isolate == "Zt05"]
    eig.C.ME24$Group[x] = "H"
  } 
  if(stri_detect(rownames(eig.C.ME24)[x], regex = "Zt09")) {
    eig.C.ME24$Pycnidia.dpi[x] =  infection.outcomes$Pycnidia..dpi.[infection.outcomes$Isolate == "Zt09"]
    eig.C.ME24$Group[x] = "H"
  } 
  if(stri_detect(rownames(eig.C.ME24)[x], regex = "Zt10")) {
    eig.C.ME24$Pycnidia.dpi[x] =  infection.outcomes$Pycnidia..dpi.[infection.outcomes$Isolate == "Zt10"]
    eig.C.ME24$Group[x] = "H"
  }
}

jpeg(filename = "Plots/eigscatterplots/C.Pycnidia.M24.jpeg")
ggplot(eig.C.ME24, aes(y=Pycnidia.dpi, x=M24)) +
  geom_smooth(method=lm , color="grey", fill='lightgrey', se=TRUE) +
  geom_point(aes(color = Group, shape = rownames(eig.C.ME24)), size = 3) +
  scale_shape_manual(values = c(15,6,19,5,17,9,18), name = "Isolates", labels = c("1A5", "1E4", "3D1", "3D7", "Zt05", "Zt09", "Zt10")) +
  ggtitle("M24.C: Pycnidia development") +
  xlab("Eigengene expression")
dev.off()

# D.ME24.Pycnidia
eig.D.ME24 = eig.D[colnames(eig.D)==c("M24")]
eig.D.ME24$Pycnidia.dpi = NA
eig.D.ME24$Group = NA
for (x in 1:length(eig.D.ME24$Pycnidia.dpi)){
  if(stri_detect(rownames(eig.D.ME24)[x], regex = "3D1")) {
    eig.D.ME24$Pycnidia.dpi[x] =  infection.outcomes$Pycnidia..dpi.[infection.outcomes$Isolate == "3D1"]
    eig.D.ME24$Group[x] = "PG"
  } 
  if(stri_detect(rownames(eig.D.ME24)[x], regex = "3D7")) {
    eig.D.ME24$Pycnidia.dpi[x] =  infection.outcomes$Pycnidia..dpi.[infection.outcomes$Isolate == "3D7"]
    eig.D.ME24$Group[x] = "PG"
  } 
  if(stri_detect(rownames(eig.D.ME24)[x], regex = "1A5")) {
    eig.D.ME24$Pycnidia.dpi[x] =  infection.outcomes$Pycnidia..dpi.[infection.outcomes$Isolate == "1A5"]
    eig.D.ME24$Group[x] = "PG"
  } 
  if(stri_detect(rownames(eig.D.ME24)[x], regex = "1E4")) {
    eig.D.ME24$Pycnidia.dpi[x] =  infection.outcomes$Pycnidia..dpi.[infection.outcomes$Isolate == "1E4"]
    eig.D.ME24$Group[x] = "PG"
  } 
  if(stri_detect(rownames(eig.D.ME24)[x], regex = "Zt05")) {
    eig.D.ME24$Pycnidia.dpi[x] =  infection.outcomes$Pycnidia..dpi.[infection.outcomes$Isolate == "Zt05"]
    eig.D.ME24$Group[x] = "H"
  } 
  if(stri_detect(rownames(eig.D.ME24)[x], regex = "Zt09")) {
    eig.D.ME24$Pycnidia.dpi[x] =  infection.outcomes$Pycnidia..dpi.[infection.outcomes$Isolate == "Zt09"]
    eig.D.ME24$Group[x] = "H"
  } 
  if(stri_detect(rownames(eig.D.ME24)[x], regex = "Zt10")) {
    eig.D.ME24$Pycnidia.dpi[x] =  infection.outcomes$Pycnidia..dpi.[infection.outcomes$Isolate == "Zt10"]
    eig.D.ME24$Group[x] = "H"
  }
}

jpeg(filename = "Plots/eigscatterplots/D.Pycnidia.M24.jpeg")
ggplot(eig.D.ME24, aes(y=Pycnidia.dpi, x=M24)) +
  geom_smooth(method=lm , color="grey", fill='lightgrey', se=TRUE) +
  geom_point(aes(color = Group, shape = rownames(eig.D.ME24)), size = 3) +
  scale_shape_manual(values = c(15,6,19,5,17,9,18), name = "Isolates", labels = c("1A5", "1E4", "3D1", "3D7", "Zt05", "Zt09", "Zt10")) +
  ggtitle("M24.D: Pycnidia development") +
  xlab("Eigengene expression")
dev.off()

```

```{r}
# calculate scaled kIM - you should have these parameters (or variations of) in your code
kIM =intramodularConnectivity(adjacency, moduleLabels.ME, scaleByMax = T)
# Add module colour assignments for each gene # 
kIM$Module = moduleLabels.ME

# Remove un-needed columns of kIM dataframe #
kIM$kOut <- NULL
kIM$kDiff <- NULL
kIM$kTotal <- NULL

# Order kIM data.frame by module and connectivity #
# Note the - sign to sort by decreasing value
kIM.reorder = kIM[order(kIM$Module, -kIM$kWithin),]
# Remove M0 rows
kIM.reorder.noGrey = subset(kIM.reorder, Module != "M0")
# Write up table
write.table(kIM.reorder.noGrey, file = "Tables/intra-intermodular_connectivity.txt", sep = "\t")
# Identify Hub genes
write.table(kIM.reorder.noGrey[kIM.reorder.noGrey$kWithin >=0.7,], file = "Tables/hub.genes.txt", sep = "\t")

```

```{r}
## Gene Significance Analysis

# For the gene significance analysis we will need normalised count data - 
datExpr2.noGrey = datExpr2
norm.counts = data.frame(t(plantData))
norm.counts$Isolate = datExpr2$Isolate
norm.counts$Stage = datExpr2$Stage

# Create data.frame of average normalized counts, gene expression values for replicates
norm.counts.avg = data.frame()
norm.counts.avg = rbind(norm.counts.avg, colMeans(
  norm.counts[1:9276][norm.counts$Isolate == "Zt05" & norm.counts$Stage == "A",], na.rm=TRUE))
norm.counts.avg = rbind(norm.counts.avg, colMeans(
  norm.counts[1:9276][norm.counts$Isolate == "Zt05" & norm.counts$Stage == "B",], na.rm=TRUE))
norm.counts.avg = rbind(norm.counts.avg, colMeans(
  norm.counts[1:9276][norm.counts$Isolate == "Zt05" & norm.counts$Stage == "C",], na.rm=TRUE))
norm.counts.avg = rbind(norm.counts.avg, colMeans(
  norm.counts[1:9276][norm.counts$Isolate == "Zt05" & norm.counts$Stage == "D",], na.rm=TRUE))
norm.counts.avg = rbind(norm.counts.avg, colMeans(
  norm.counts[1:9276][norm.counts$Isolate == "Zt09" & norm.counts$Stage == "A",], na.rm=TRUE))
norm.counts.avg = rbind(norm.counts.avg, colMeans(
  norm.counts[1:9276][norm.counts$Isolate == "Zt09" & norm.counts$Stage == "B",], na.rm=TRUE))
norm.counts.avg = rbind(norm.counts.avg, colMeans(
  norm.counts[1:9276][norm.counts$Isolate == "Zt09" & norm.counts$Stage == "C",], na.rm=TRUE))
norm.counts.avg = rbind(norm.counts.avg, colMeans(
  norm.counts[1:9276][norm.counts$Isolate == "Zt09" & norm.counts$Stage == "D",], na.rm=TRUE))
norm.counts.avg = rbind(norm.counts.avg, colMeans(
  norm.counts[1:9276][norm.counts$Isolate == "Zt10" & norm.counts$Stage == "A",], na.rm=TRUE))
norm.counts.avg = rbind(norm.counts.avg, colMeans(
  norm.counts[1:9276][norm.counts$Isolate == "Zt10" & norm.counts$Stage == "B",], na.rm=TRUE))
norm.counts.avg = rbind(norm.counts.avg, colMeans(
  norm.counts[1:9276][norm.counts$Isolate == "Zt10" & norm.counts$Stage == "C",], na.rm=TRUE))
norm.counts.avg = rbind(norm.counts.avg, colMeans(
  norm.counts[1:9276][norm.counts$Isolate == "Zt10" & norm.counts$Stage == "D",], na.rm=TRUE))
norm.counts.avg = rbind(norm.counts.avg, colMeans(
  norm.counts[1:9276][norm.counts$Isolate == "3D1" & norm.counts$Stage == "A",], na.rm=TRUE))
norm.counts.avg = rbind(norm.counts.avg, colMeans(
  norm.counts[1:9276][norm.counts$Isolate == "3D1" & norm.counts$Stage == "B",], na.rm=TRUE))
norm.counts.avg = rbind(norm.counts.avg, colMeans(
  norm.counts[1:9276][norm.counts$Isolate == "3D1" & norm.counts$Stage == "C",], na.rm=TRUE))
norm.counts.avg = rbind(norm.counts.avg, colMeans(
  norm.counts[1:9276][norm.counts$Isolate == "3D1" & norm.counts$Stage == "D",], na.rm=TRUE))
norm.counts.avg = rbind(norm.counts.avg, colMeans(
  norm.counts[1:9276][norm.counts$Isolate == "3D7" & norm.counts$Stage == "A",], na.rm=TRUE))
norm.counts.avg = rbind(norm.counts.avg, colMeans(
  norm.counts[1:9276][norm.counts$Isolate == "3D7" & norm.counts$Stage == "B",], na.rm=TRUE))
norm.counts.avg = rbind(norm.counts.avg, colMeans(
  norm.counts[1:9276][norm.counts$Isolate == "3D7" & norm.counts$Stage == "C",], na.rm=TRUE))
norm.counts.avg = rbind(norm.counts.avg, colMeans(
  norm.counts[1:9276][norm.counts$Isolate == "3D7" & norm.counts$Stage == "D",], na.rm=TRUE))
norm.counts.avg = rbind(norm.counts.avg, colMeans(
  norm.counts[1:9276][norm.counts$Isolate == "1A5" & norm.counts$Stage == "A",], na.rm=TRUE))
norm.counts.avg = rbind(norm.counts.avg, colMeans(
  norm.counts[1:9276][norm.counts$Isolate == "1A5" & norm.counts$Stage == "B",], na.rm=TRUE))
norm.counts.avg = rbind(norm.counts.avg, colMeans(
  norm.counts[1:9276][norm.counts$Isolate == "1A5" & norm.counts$Stage == "C",], na.rm=TRUE))
norm.counts.avg = rbind(norm.counts.avg, colMeans(
  norm.counts[1:9276][norm.counts$Isolate == "1A5" & norm.counts$Stage == "D",], na.rm=TRUE))
norm.counts.avg = rbind(norm.counts.avg, colMeans(
  norm.counts[1:9276][norm.counts$Isolate == "1E4" & norm.counts$Stage == "A",], na.rm=TRUE))
norm.counts.avg = rbind(norm.counts.avg, colMeans(
  norm.counts[1:9276][norm.counts$Isolate == "1E4" & norm.counts$Stage == "B",], na.rm=TRUE))
norm.counts.avg = rbind(norm.counts.avg, colMeans(
  norm.counts[1:9276][norm.counts$Isolate == "1E4" & norm.counts$Stage == "C",], na.rm=TRUE))
norm.counts.avg = rbind(norm.counts.avg, colMeans(
  norm.counts[1:9276][norm.counts$Isolate == "1E4" & norm.counts$Stage == "D",], na.rm=TRUE))
names(norm.counts.avg) = names(norm.counts[1:9276])
rownames(norm.counts.avg) = unique(paste(datExpr2.noGrey$Isolate, datExpr2.noGrey$Stage, sep = "_"))

# Split table into that of stages
norm.counts.A = data.frame(norm.counts.avg[stri_detect(rownames(norm.counts.avg), regex = "_A"),], 
                           row.names=c('Zt05', 'Zt09', 'Zt10', '3D1', '3D7', '1A5', '1E4'))
norm.counts.B = data.frame(norm.counts.avg[stri_detect(rownames(norm.counts.avg), regex = "_B"),], 
                           row.names=c('Zt05', 'Zt09', 'Zt10', '3D1', '3D7', '1A5', '1E4'))
norm.counts.C = data.frame(norm.counts.avg[stri_detect(rownames(norm.counts.avg), regex = "_C"),], 
                           row.names=c('Zt05', 'Zt09', 'Zt10', '3D1', '3D7', '1A5', '1E4'))
norm.counts.D = data.frame(norm.counts.avg[stri_detect(rownames(norm.counts.avg), regex = "_D"),], 
                           row.names=c('Zt05', 'Zt09', 'Zt10', '3D1', '3D7', '1A5', '1E4'))

# Now we can do the same correlation analysis but for individual genes rather than eignegenes
# Add the p.adjust value to account for false-positives (large range of experiments)
## Necrosis..dpi.
GS.A.necrosis = corAndPvalue(norm.counts.A, infection.outcomes$Necrosis..dpi., 
                             use = "pairwise.complete.obs", alternative = c("two.sided"))
GS.A.necrosis$p.adjust = as.matrix(unlist(lapply(GS.A.necrosis$p, function (x) {p.adjust(x, method = "BH")})), ncol = 1)
rownames(GS.A.necrosis$p.adjust) = rownames(GS.A.necrosis$p)

GS.B.necrosis = corAndPvalue(norm.counts.B, infection.outcomes$Necrosis..dpi., 
                             use = "pairwise.complete.obs", alternative = c("two.sided"))
GS.B.necrosis$p.adjust = as.matrix(unlist(lapply(GS.B.necrosis$p, function (x) {p.adjust(x, method = "BH")})), ncol = 1)
rownames(GS.B.necrosis$p.adjust) = rownames(GS.B.necrosis$p)

GS.C.necrosis = corAndPvalue(norm.counts.C, infection.outcomes$Necrosis..dpi., 
                             use = "pairwise.complete.obs", alternative = c("two.sided"))
GS.C.necrosis$p.adjust = as.matrix(unlist(lapply(GS.C.necrosis$p, function (x) {p.adjust(x, method = "BH")})), ncol = 1)
rownames(GS.C.necrosis$p.adjust) = rownames(GS.C.necrosis$p)

GS.D.necrosis = corAndPvalue(norm.counts.D, infection.outcomes$Necrosis..dpi., 
                             use = "pairwise.complete.obs", alternative = c("two.sided"))
GS.D.necrosis$p.adjust = as.matrix(unlist(lapply(GS.D.necrosis$p, function (x) {p.adjust(x, method = "BH")})), ncol = 1)
rownames(GS.D.necrosis$p.adjust) = rownames(GS.D.necrosis$p)

## Pycnidia..dpi.
GS.A.pycnidia = corAndPvalue(norm.counts.A, infection.outcomes$Pycnidia..dpi., 
                             use = "pairwise.complete.obs", alternative = c("two.sided"))
GS.A.pycnidia$p.adjust = as.matrix(unlist(lapply(GS.A.pycnidia$p, function (x) {p.adjust(x, method = "BH")})), ncol = 1)
rownames(GS.A.pycnidia$p.adjust) = rownames(GS.A.pycnidia$p)

GS.B.pycnidia = corAndPvalue(norm.counts.B, infection.outcomes$Pycnidia..dpi., 
                             use = "pairwise.complete.obs", alternative = c("two.sided"))
GS.B.pycnidia$p.adjust = as.matrix(unlist(lapply(GS.B.pycnidia$p, function (x) {p.adjust(x, method = "BH")})), ncol = 1)
rownames(GS.B.pycnidia$p.adjust) = rownames(GS.B.pycnidia$p)

GS.C.pycnidia = corAndPvalue(norm.counts.C, infection.outcomes$Pycnidia..dpi., 
                             use = "pairwise.complete.obs", alternative = c("two.sided"))
GS.C.pycnidia$p.adjust = as.matrix(unlist(lapply(GS.C.pycnidia$p, function (x) {p.adjust(x, method = "BH")})), ncol = 1)
rownames(GS.C.pycnidia$p.adjust) = rownames(GS.C.pycnidia$p)

GS.D.pycnidia = corAndPvalue(norm.counts.D, infection.outcomes$Pycnidia..dpi., 
                             use = "pairwise.complete.obs", alternative = c("two.sided"))
GS.D.pycnidia$p.adjust = as.matrix(unlist(lapply(GS.D.pycnidia$p, function (x) {p.adjust(x, method = "BH")})), ncol = 1)
rownames(GS.D.pycnidia$p.adjust) = rownames(GS.D.pycnidia$p)

#Necrosis lvl
GS.A.necrosisLvl = corAndPvalue(norm.counts.A, infection.outcomes$Necrosis.level, 
                             use = "pairwise.complete.obs", alternative = c("two.sided"))
GS.A.necrosisLvl$p.adjust = as.matrix(unlist(lapply(GS.A.necrosisLvl$p, function (x) {p.adjust(x, method = "BH")})), ncol = 1)
rownames(GS.A.necrosisLvl$p.adjust) = rownames(GS.A.necrosisLvl$p)

GS.B.necrosisLvl = corAndPvalue(norm.counts.B, infection.outcomes$Necrosis.level, 
                             use = "pairwise.complete.obs", alternative = c("two.sided"))
GS.B.necrosisLvl$p.adjust = as.matrix(unlist(lapply(GS.B.necrosisLvl$p, function (x) {p.adjust(x, method = "BH")})), ncol = 1)
rownames(GS.B.necrosisLvl$p.adjust) = rownames(GS.B.necrosisLvl$p)

GS.C.necrosisLvl = corAndPvalue(norm.counts.C, infection.outcomes$Necrosis.level, 
                             use = "pairwise.complete.obs", alternative = c("two.sided"))
GS.C.necrosisLvl$p.adjust = as.matrix(unlist(lapply(GS.C.necrosisLvl$p, function (x) {p.adjust(x, method = "BH")})), ncol = 1)
rownames(GS.C.necrosisLvl$p.adjust) = rownames(GS.C.necrosisLvl$p)

GS.D.necrosisLvl = corAndPvalue(norm.counts.D, infection.outcomes$Necrosis.level, 
                             use = "pairwise.complete.obs", alternative = c("two.sided"))
GS.D.necrosisLvl$p.adjust = as.matrix(unlist(lapply(GS.D.necrosisLvl$p, function (x) {p.adjust(x, method = "BH")})), ncol = 1)
rownames(GS.D.necrosisLvl$p.adjust) = rownames(GS.D.necrosisLvl$p)

#Early onset
GS.A.earlyOnset = corAndPvalue(norm.counts.A, infection.outcomes$Early.onset, 
                             use = "pairwise.complete.obs", alternative = c("two.sided"))
GS.A.earlyOnset$p.adjust = as.matrix(unlist(lapply(GS.A.earlyOnset$p, function (x) {p.adjust(x, method = "BH")})), ncol = 1)
rownames(GS.A.earlyOnset$p.adjust) = rownames(GS.A.earlyOnset$p)

GS.B.earlyOnset = corAndPvalue(norm.counts.B, infection.outcomes$Early.onset, 
                             use = "pairwise.complete.obs", alternative = c("two.sided"))
GS.B.earlyOnset$p.adjust = as.matrix(unlist(lapply(GS.B.earlyOnset$p, function (x) {p.adjust(x, method = "BH")})), ncol = 1)
rownames(GS.B.earlyOnset$p.adjust) = rownames(GS.B.earlyOnset$p)

GS.C.earlyOnset = corAndPvalue(norm.counts.C, infection.outcomes$Early.onset, 
                             use = "pairwise.complete.obs", alternative = c("two.sided"))
GS.C.earlyOnset$p.adjust = as.matrix(unlist(lapply(GS.C.earlyOnset$p, function (x) {p.adjust(x, method = "BH")})), ncol = 1)
rownames(GS.C.earlyOnset$p.adjust) = rownames(GS.C.earlyOnset$p)

GS.D.earlyOnset = corAndPvalue(norm.counts.D, infection.outcomes$Early.onset, 
                             use = "pairwise.complete.obs", alternative = c("two.sided"))
GS.D.earlyOnset$p.adjust = as.matrix(unlist(lapply(GS.D.earlyOnset$p, function (x) {p.adjust(x, method = "BH")})), ncol = 1)
rownames(GS.D.earlyOnset$p.adjust) = rownames(GS.D.earlyOnset$p)

#### MODULE GENE TABLES ####
# Make cor & p.adjust lists
GS.A.cor = cbind(GS.A.necrosis$cor, GS.A.pycnidia$cor, GS.A.necrosisLvl$cor, GS.A.earlyOnset$cor)
GS.B.cor = cbind(GS.B.necrosis$cor, GS.B.pycnidia$cor, GS.B.necrosisLvl$cor, GS.B.earlyOnset$cor)
GS.C.cor = cbind(GS.C.necrosis$cor, GS.C.pycnidia$cor, GS.C.necrosisLvl$cor, GS.C.earlyOnset$cor)
GS.D.cor = cbind(GS.D.necrosis$cor, GS.D.pycnidia$cor, GS.D.necrosisLvl$cor, GS.D.earlyOnset$cor)
GS.A.pValue = cbind(GS.A.necrosis$p.adjust, GS.A.pycnidia$p.adjust, GS.A.necrosisLvl$p.adjust, GS.A.earlyOnset$p.adjust)
GS.B.pValue = cbind(GS.B.necrosis$p.adjust, GS.B.pycnidia$p.adjust, GS.B.necrosisLvl$p.adjust, GS.B.earlyOnset$p.adjust)
GS.C.pValue = cbind(GS.C.necrosis$p.adjust, GS.C.pycnidia$p.adjust, GS.C.necrosisLvl$p.adjust, GS.C.earlyOnset$p.adjust)
GS.D.pValue = cbind(GS.D.necrosis$p.adjust, GS.D.pycnidia$p.adjust, GS.D.necrosisLvl$p.adjust, GS.D.earlyOnset$p.adjust)

outcomes.list = list("necrosis_", "pycnidia_", "necrosisLvl_", "earlyOnset_")
#### INFECTION STAGE A ####
for (i in 1:4) {
  GS.A.significant = rownames(GS.A.pValue)[GS.A.pValue[,i]<0.05]
  GS.A.subset = GS.A.pValue[,i][rownames(GS.A.pValue) %in% GS.A.significant]
  GS.A.subset.df = data.frame(GS.A.subset)
  colnames(GS.A.subset.df) = "p.Adjust"
  GS.A.subset.df$cor = GS.A.cor[,i][rownames(GS.A.cor) %in% rownames(GS.A.cor)[GS.A.pValue[,i]<0.05]]
  GS.A.subset.df$kWithin = NA
  GS.A.subset.df$module = NA
  for (x in 1:length(rownames(GS.A.subset.df))) {
    if (rownames(GS.A.subset.df)[x] ==
        gene.module.assignments$ID[rownames(GS.A.subset.df)[x] == gene.module.assignments$ID]) {
      GS.A.subset.df$module[x] =
        gene.module.assignments$New.Module.Assignment[rownames(GS.A.subset.df)[x] ==
                                                        gene.module.assignments$ID]
    }
    if (rownames(GS.A.subset.df)[x] ==
        rownames(kIM.reorder)[rownames(GS.A.subset.df)[x] ==
        rownames(kIM.reorder)]) {
      GS.A.subset.df$kWithin[x] =
        kIM.reorder$kWithin[rownames(GS.A.subset.df)[x] == rownames(kIM.reorder)]
    }
  }
  GS.A.subset.df.noGrey = GS.A.subset.df[!GS.A.subset.df$module == "M0",]
  GS.A.subset.df.noGrey.reorder = GS.A.subset.df.noGrey[order(GS.A.subset.df.noGrey$module, -GS.A.subset.df.noGrey$kWithin),]
  write.csv(GS.A.subset.df.noGrey.reorder, file = paste("Tables/gene_significance/stage_A/", outcomes.list[i],"A.csv", sep = ""), row.names = T)
}

#### INFECTION STAGE B ####
for (i in 1:4) {
  GS.B.significant = rownames(GS.B.pValue)[GS.B.pValue[,i]<0.05]
  GS.B.subset = GS.B.pValue[,i][rownames(GS.B.pValue) %in% GS.B.significant]
  GS.B.subset.df = data.frame(GS.B.subset)
  colnames(GS.B.subset.df) = "p.Adjust"
  GS.B.subset.df$cor = GS.B.cor[,i][rownames(GS.B.cor) %in% rownames(GS.B.cor)[GS.B.pValue[,i]<0.05]]
  GS.B.subset.df$kWithin = NA
  GS.B.subset.df$module = NA
  for (x in 1:length(rownames(GS.B.subset.df))) {
    if (rownames(GS.B.subset.df)[x] ==
        gene.module.assignments$ID[rownames(GS.B.subset.df)[x] == gene.module.assignments$ID]) {
      GS.B.subset.df$module[x] =
        gene.module.assignments$New.Module.Assignment[rownames(GS.B.subset.df)[x] ==
                                                        gene.module.assignments$ID]
    }
    if (rownames(GS.B.subset.df)[x] ==
        rownames(kIM.reorder)[rownames(GS.B.subset.df)[x] ==
        rownames(kIM.reorder)]) {
      GS.B.subset.df$kWithin[x] =
        kIM.reorder$kWithin[rownames(GS.B.subset.df)[x] == rownames(kIM.reorder)]
    }
  }
  GS.B.subset.df.noGrey = GS.B.subset.df[!GS.B.subset.df$module == "M0",]
  GS.B.subset.df.noGrey.reorder = GS.B.subset.df.noGrey[order(GS.B.subset.df.noGrey$module, -GS.B.subset.df.noGrey$kWithin),]
  write.csv(GS.B.subset.df.noGrey.reorder, file = paste("Tables/gene_significance/stage_B/", outcomes.list[i],"B.csv", sep = ""), row.names = T)
}

#### INFECTION STAGE C ####
for (i in 1:4) {
  GS.C.significant = rownames(GS.C.pValue)[GS.C.pValue[,i]<0.05]
  GS.C.subset = GS.C.pValue[,i][rownames(GS.C.pValue) %in% GS.C.significant]
  GS.C.subset.df = data.frame(GS.C.subset)
  colnames(GS.C.subset.df) = "p.Adjust"
  GS.C.subset.df$cor = GS.C.cor[,i][rownames(GS.C.cor) %in% rownames(GS.C.cor)[GS.C.pValue[,i]<0.05]]
  GS.C.subset.df$kWithin = NA
  GS.C.subset.df$module = NA
  for (x in 1:length(rownames(GS.C.subset.df))) {
    if (rownames(GS.C.subset.df)[x] ==
        gene.module.assignments$ID[rownames(GS.C.subset.df)[x] == gene.module.assignments$ID]) {
      GS.C.subset.df$module[x] =
        gene.module.assignments$New.Module.Assignment[rownames(GS.C.subset.df)[x] ==
                                                        gene.module.assignments$ID]
    }
    if (rownames(GS.C.subset.df)[x] ==
        rownames(kIM.reorder)[rownames(GS.C.subset.df)[x] ==
        rownames(kIM.reorder)]) {
      GS.C.subset.df$kWithin[x] =
        kIM.reorder$kWithin[rownames(GS.C.subset.df)[x] == rownames(kIM.reorder)]
    }
  }
  GS.C.subset.df.noGrey = GS.C.subset.df[!GS.C.subset.df$module == "M0",]
  GS.C.subset.df.noGrey.reorder = GS.C.subset.df.noGrey[order(GS.C.subset.df.noGrey$module, -GS.C.subset.df.noGrey$kWithin),]
  write.csv(GS.C.subset.df.noGrey.reorder, file = paste("Tables/gene_significance/stage_C/", outcomes.list[i],"C.csv", sep = ""), row.names = T)
}

#### INFECTION STAGE D ####
for (i in 1:4) {
  GS.D.significant = rownames(GS.D.pValue)[GS.D.pValue[,i]<0.05]
  GS.D.subset = GS.D.pValue[,i][rownames(GS.D.pValue) %in% GS.D.significant]
  GS.D.subset.df = data.frame(GS.D.subset)
  colnames(GS.D.subset.df) = "p.Adjust"
  GS.D.subset.df$cor = GS.D.cor[,i][rownames(GS.D.cor) %in% rownames(GS.D.cor)[GS.D.pValue[,i]<0.05]]
  GS.D.subset.df$kWithin = NA
  GS.D.subset.df$module = NA
  for (x in 1:length(rownames(GS.D.subset.df))) {
    if (rownames(GS.D.subset.df)[x] ==
        gene.module.assignments$ID[rownames(GS.D.subset.df)[x] == gene.module.assignments$ID]) {
      GS.D.subset.df$module[x] =
        gene.module.assignments$New.Module.Assignment[rownames(GS.D.subset.df)[x] ==
                                                        gene.module.assignments$ID]
    }
    if (rownames(GS.D.subset.df)[x] ==
        rownames(kIM.reorder)[rownames(GS.D.subset.df)[x] ==
        rownames(kIM.reorder)]) {
      GS.D.subset.df$kWithin[x] =
        kIM.reorder$kWithin[rownames(GS.D.subset.df)[x] == rownames(kIM.reorder)]
    }
  }
  GS.D.subset.df.noGrey = GS.D.subset.df[!GS.D.subset.df$module == "M0",]
  GS.D.subset.df.noGrey.reorder = GS.D.subset.df.noGrey[order(GS.D.subset.df.noGrey$module, -GS.D.subset.df.noGrey$kWithin),]
  write.csv(GS.D.subset.df.noGrey.reorder, file = paste("Tables/gene_significance/stage_D/", outcomes.list[i],"D.csv", sep = ""), row.names = T)
}


#### TABLES OF IDENTIFIED SIGNIFICANT GENES ####

# Find tables with significant data and pull out these modules
pycnidia.A = read.table("Tables/gene_significance/stage_A/pycnidia_A.csv", header = T, sep = ",")
pycnidia.B = read.table("Tables/gene_significance/stage_B/pycnidia_B.csv", header = T, sep = ",")
necrosisLvl.B = read.table("Tables/gene_significance/stage_B/necrosisLvl_B.csv", header = T, sep = ",")
earlyOnset.B = read.table("Tables/gene_significance/stage_B/earlyOnset_B.csv", header = T, sep = ",")
necrosis.C = read.table("Tables/gene_significance/stage_C/necrosis_C.csv", header = T, sep = ",")
pycnidia.C = read.table("Tables/gene_significance/stage_C/pycnidia_C.csv", header = T, sep = ",")
necrosisLvl.C = read.table("Tables/gene_significance/stage_C/necrosisLvl_C.csv", header = T, sep = ",")
earlyOnset.C = read.table("Tables/gene_significance/stage_C/earlyOnset_C.csv", header = T, sep = ",")
pycnidia.D = read.table("Tables/gene_significance/stage_D/pycnidia_D.csv", header = T, sep = ",")

# Extract specific modules
pycnidia.A.ME24 = pycnidia.A[pycnidia.A$module == "M24",]
pycnidia.B.ME24 = pycnidia.B[pycnidia.B$module == "M24",]
necrosisLvl.B.ME13 = necrosisLvl.B[necrosisLvl.B$module == "M13",]
earlyOnset.B.ME13 = earlyOnset.B[earlyOnset.B$module == "M13",]
necrosis.C.ME13 = necrosis.C[necrosis.C$module == "M13",]
pycnidia.C.ME24 = pycnidia.C[pycnidia.C$module == "M24",]
necrosisLvl.C.ME6 = necrosisLvl.C[necrosisLvl.C$module == "M6",]
earlyOnset.C.ME6 = earlyOnset.C[earlyOnset.C$module == "M6",]
necrosisLvl.C.ME13 = necrosisLvl.C[necrosisLvl.C$module == "M13",]
earlyOnset.C.ME13 = earlyOnset.C[earlyOnset.C$module == "M13",]
pycnidia.D.ME24 = pycnidia.D[pycnidia.D$module == "M24",]

# Make list of tables
signif.list = list(pycnidia.A.ME24, pycnidia.B.ME24, necrosisLvl.B.ME13, earlyOnset.B.ME13, necrosis.C.ME13, pycnidia.C.ME24, necrosisLvl.C.ME6, earlyOnset.C.ME6, necrosisLvl.C.ME13, earlyOnset.C.ME13, pycnidia.D.ME24)
signif.names.list  = list("pycnidia.A.M24", "pycnidia.B.M24", "necrosisLvl.B.M13", "earlyOnset.B.M13", "necrosis.C.M13", "pycnidia.C.M24", "necrosisLvl.C.M6", "earlyOnset.C.M6", "necrosisLvl.C.M13", "earlyOnset.C.M13", "pycnidia.D.M24")
new.signif.list = list()
# signif values
for (x in 1:length(signif.list)) {
  signif.list[[x]]$p.Adjust = format(signif.list[[x]]$p.Adjust, scientific = TRUE, digits = 2)
  signif.list[[x]]$cor = signif(signif.list[[x]]$cor, digits = 2)
  signif.list[[x]]$kWithin = format(signif.list[[x]]$kWithin, digits = 2)
  write.csv(signif.list[[x]], file = paste("Tables/gene_significance/extracted_modules/", signif.names.list[x],".csv", sep = ""), row.names = F)
}

```

